import { Role } from "@prisma/client";
import { cookies } from "next/headers";

import {
  DEV_AUTH_COOKIE,
  type DevAuthClientSession,
  type DevAuthRole,
  isAllowedDevRole,
  isDevAuthEnabled,
  sanitizeDevAuthEmail,
  sanitizeDevAuthName,
} from "@/lib/dev-auth";
import { prisma } from "@/lib/prisma";

const DEV_TEACHER_ID = "dev-teacher";

function defaultTeacherPayload(): DevAuthCookiePayload {
  return {
    id: DEV_TEACHER_ID,
    role: "TEACHER",
    name: defaultNameForRole("TEACHER"),
    email: defaultEmailForRole("TEACHER"),
  };
}

export type DevAuthCookiePayload = DevAuthClientSession & {
  id: string;
};

export async function getDevAuthCookie(): Promise<DevAuthCookiePayload | null> {
  if (!isDevAuthEnabled()) {
    return null;
  }

  const store = await cookies();
  const raw = store.get(DEV_AUTH_COOKIE)?.value;

  if (!raw) {
    return null;
  }

  try {
    const parsed = JSON.parse(raw) as Partial<DevAuthCookiePayload>;

    if (!parsed || !parsed.role || !isAllowedDevRole(parsed.role)) {
      return null;
    }

    const role = parsed.role;
    const name = sanitizeDevAuthName(parsed.name);
    const email = sanitizeDevAuthEmail(parsed.email);
    const id = typeof parsed.id === "string" && parsed.id ? parsed.id : `dev-${role.toLowerCase()}`;

    return {
      role,
      name: name || defaultNameForRole(role),
      email: email || defaultEmailForRole(role),
      id,
    };
  } catch {
    return null;
  }
}

export async function setDevAuthCookie(payload: DevAuthCookiePayload) {
  if (!isDevAuthEnabled()) {
    return;
  }

  const store = await cookies();
  store.set(DEV_AUTH_COOKIE, JSON.stringify(payload), {
    httpOnly: true,
    sameSite: "lax",
    path: "/",
    secure: false,
  });
}

export async function clearDevAuthCookie() {
  if (!isDevAuthEnabled()) {
    return;
  }

  const store = await cookies();
  store.delete(DEV_AUTH_COOKIE);
}

export function defaultEmailForRole(role: DevAuthRole) {
  return role === "TEACHER" ? "teacher.dev@example.com" : "student.dev@example.com";
}

export function defaultNameForRole(role: DevAuthRole) {
  return role === "TEACHER" ? "Dev Teacher" : "Dev Student";
}

export function toPrismaRole(role: DevAuthRole): Role {
  return role === "TEACHER" ? Role.TEACHER : Role.STUDENT;
}

export function buildDevAuthCookiePayload(input: {
  role: DevAuthRole;
  name?: string;
  email?: string;
}): DevAuthCookiePayload {
  const role = input.role;

  return {
    id: `dev-${role.toLowerCase()}`,
    role,
    name: sanitizeDevAuthName(input.name) || defaultNameForRole(role),
    email: sanitizeDevAuthEmail(input.email) || defaultEmailForRole(role),
  };
}

export async function ensureDevUser(payload: DevAuthCookiePayload) {
  if (!isDevAuthEnabled()) {
    return null;
  }

  const role = toPrismaRole(payload.role);

  try {
    if (!prisma.user?.upsert) {
      return null;
    }

    const user = await prisma.user.upsert({
      where: { id: payload.id },
      update: {
        email: payload.email,
        name: payload.name,
        role,
      },
      create: {
        id: payload.id,
        email: payload.email,
        name: payload.name,
        role,
      },
    });

    if (role === Role.TEACHER) {
      await ensureDevTeacherClass(user.id, payload);
    } else {
      await ensureDevStudentEnrollment(user.id);
    }

    return user;
  } catch (error) {
    console.warn("Failed to ensure dev user", error);
    return null;
  }
}

async function ensureDevTeacherClass(
  teacherId: string,
  payload: DevAuthCookiePayload
) {
  if (!prisma.class?.findFirst || !prisma.class?.create) {
    return null;
  }

  const existing = await prisma.class.findFirst({
    where: { teacherId },
  });

  if (existing) {
    return existing;
  }

  const joinCode = generateDevJoinCode();

  try {
    return await prisma.class.create({
      data: {
        name: `${payload.name}'s Dev Class`,
        description: "Autogenerated class for local dev impersonation.",
        joinCode,
        teacherId,
      },
    });
  } catch (error) {
    console.warn("Failed to create dev teacher class", error);
    return null;
  }
}

function generateDevJoinCode() {
  return `DEV-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
}

async function ensureDevStudentEnrollment(studentId: string) {
  if (!prisma.class?.findFirst || !prisma.classEnrollment?.upsert) {
    return;
  }

  let teacherClass = await prisma.class.findFirst({
    where: { teacherId: DEV_TEACHER_ID },
  });

  if (!teacherClass) {
    const teacherPayload = defaultTeacherPayload();
    teacherClass = await ensureDevTeacherClass(teacherPayload.id, teacherPayload) ?? null;
  }

  if (!teacherClass) {
    return;
  }

  try {
    await prisma.classEnrollment.upsert({
      where: {
        classId_studentId: {
          classId: teacherClass.id,
          studentId,
        },
      },
      update: {},
      create: {
        classId: teacherClass.id,
        studentId,
      },
    });
  } catch (error) {
    console.warn("Failed to ensure dev student enrollment", error);
  }
}
